spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/project.mv.db
    username: sa
    password:
    driverClassName: org.h2.Driver

